#!/usr/bin/env bash

CURRENT="/home/vagrant/builds/willdurand/Propel2"
PROPEL_GEN="$CURRENT/tools/generator/bin/propel-gen"

cd "$CURRENT/tests/Fixtures/bookstore"
$PROPEL_GEN convert-conf
$PROPEL_GEN insert-sql
cd "$CURRENT"

cd "$CURRENT/tests/Fixtures/bookstore-packaged"
$PROPEL_GEN convert-conf
$PROPEL_GEN insert-sql
cd "$CURRENT"

cd "$CURRENT/tests/Fixtures/namespaced"
$PROPEL_GEN convert-conf
$PROPEL_GEN insert-sql
cd "$CURRENT"

cd "$CURRENT/tests/Fixtures/schemas"
$PROPEL_GEN convert-conf
$PROPEL_GEN insert-sql
cd "$CURRENT"
