version: 2
jobs:
  build:
    docker:
      - image: circleci/php:7.1-node-browsers
    steps:
      - checkout
      - run: sudo composer self-update
      - run: composer install -n --prefer-dist
      - run: echo 'memory_limit = -1' >> /usr/local/etc/php/conf.d/docker-php-memlimit.ini
      - run: if [ "$CIRCLE_NODE_INDEX" = "1" ]; then ./tests/bin/setup.mysql.sh; fi
      - run: if [ "$CIRCLE_NODE_INDEX" = "2" ]; then ./tests/bin/setup.pgsql.sh; fi
      - run: ./tests/bin/circleci.sh
    parallelism: 2

notify:
  webhooks:
    # A list of hook hashes, containing the url field
    - url: http://propel.jarves.io/build.php
    - url: https://webhooks.gitter.im/e/206efe76e183f9ade489
