version: 2
jobs:
  build:
    machine:
      environment:
        DB_USER: ubuntu
        DB_NAME: circle_test
      php:
        version: 7.0
    steps:
      - checkout
      - run: composer install -n --prefer-dist
      - run: if [ "$CIRCLE_NODE_INDEX" = "1" ]; then ./tests/bin/setup.mysql.sh; fi
      - run: if [ "$CIRCLE_NODE_INDEX" = "2" ]; then ./tests/bin/setup.pgsql.sh; fi
      - run: ./tests/bin/circleci.sh

notify:
  webhooks:
    # A list of hook hashes, containing the url field
    - url: http://propel.jarves.io/build.php
    - url: https://webhooks.gitter.im/e/206efe76e183f9ade489
