<?php

// Create empty stub object class which extends the Base class created in Object.tpl.
//
// $Id: ExtensionObject.tpl,v 1.5 2004/10/06 16:54:47 hlellelid Exp $

echo '<' . '?' . 'php';


$interface = ClassTools::getInterface($table);

if (!empty($interface)) {
?>

require_once '<?php echo ClassTools::getFilePath($interface) ?>';

<?php
}

$db = $table->getDatabase();
if($table->getPackage()) {
    $package = $table->getPackage();
} else {
    $package = $targetPackage;
}

$abstract = "";
if ($table->isAbstract()) {
    $abstract = "abstract ";
}
?>

require_once '<?php echo ClassTools::getFilePath($pkbase, $basePrefix . $table->getPhpName()) ?>';

/** 
 * The skeleton for this class was autogenerated by Propel <?php if ($addTimeStamp) { ?> on:
 *
 * [<?php echo $now ?>]
 *
<?php } ?>
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package <?php echo $package ?> 
 */
<?php echo $abstract ?>class <?php echo $table->getPhpName() ?> extends <?php echo $basePrefix . $table->getPhpName() ?><?php if (!empty($interface)) { ?> implements <?php echo ClassTools::classname($interface) ?><?php } ?> {

}
